apiVersion: v1
kind: pod 
metadata:
 name: hello-pod
name: Namespace
spec:
  containers: 
    - name: hello-pod
      image: nginx
      # here with this line port will not opened , just for information
      ports:
         - containerport: 80