apiVersion: v1
kind: Pod 
metadata:
 name: labels-demo
 labels:
   environment: dev
   app: nginx 
spec:
  containers: 
    - name: labels-demo
      image: nginx
      ports:
         - containerPort: 80 