apiVersion: v1
kind: Pod 
metadata:
 name: annotations-demo
 labels:
  environment: dev
  app: nginx 
 annotations:
   imageregistry: "https://hub.docker.com/"
   com.project: "devops"
spec:
  containers: 
  - name: annotations-demo
    image: nginx
    ports:
     - containerPort: 80 