apiVersion: v1
kind: Pod 
metadata:
 name: hello-pod
 
spec:
  containers: 
  - name: hello-pod
    image: nginx
      # here with this line port will not opened , just for information
    ports:
    - containerPort: 80
         resources:
            request:
              memory: "250mi"  
              cpu: "100m"   
            limits:
               memory: "500mi"
               cpu: "200m"