apiVersion: v1
kind: Pod 
metadata:
 name: hello-pod-5
spec:
  containers: 
  - name: hello-pod-5
    image: nginx
    ports:
    - containerPort: 80
    env: 
    - name: course
      valueFrom:
        configMapKeyRef:
            name: devops-config
            key: course
    - name: trainer
      valueFrom:
        configMapKeyRef:
            name: devops-config
            key : trainer 