apiVersion: v1
kind: Pod 
metadata:
 name: hello-pod-2
spec:
  containers: 
  - name: hello-pod-2
    image: nginx
    ports:
    - containerPort: 80
    env: 
      - name: values
        valueFrom:
          configMapKeyRef:
            name: devops-config
            key: course
      - name: values
        valueFrom:
          configMapKeyRef:
            name: devops-config
            key : trainer 