apiVersion: v1
kind: pod 
metadata:
 name: hello-pod-3
spec:
  containers: 
    - name: hello-pod-3
      image: nginx
      ports:
      - containerport: 80
      envFrom:
    - secretRef:
        name: devops-secret
      